table SalesData
	lineageTag: dfa23114-78ca-423c-bbb2-b69aec8566d9

	measure Sales_ = Sum(SalesData[Sales])
		formatString: 0
		lineageTag: c6256db7-9708-4733-b9f2-ad7300a25cd3

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ac7fc063-4084-4a16-9ccb-697ad61efc6b
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 8d3a9197-d70e-4783-ac05-c241a657dcd7
			defaultHierarchy: LocalDateTable_d9b0b5b2-07a6-46f4-a1fb-342f9378637e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Product
		dataType: string
		lineageTag: 50b70cac-100f-47f8-a682-30b891d11537
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 5e3b8ec9-70b8-4fb7-b472-52a23ae1f524
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: adfbb869-0e28-4668-b23d-eee558df2d08
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: int64
		formatString: 0
		lineageTag: c272ff8b-8f56-412b-b4f3-ac1f3b276ee4
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	partition SalesData = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jassi\Downloads\simple_sales.xlsx"), null, true),
				    SalesData_Sheet = Source{[Item="SalesData",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(SalesData_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Product", type text}, {"Category", type text}, {"City", type text}, {"Sales", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

